version: '3'
services:
   segmentation_microservice:
      image: node:16-alpine
      container_name: segmentation_microservice
      working_dir: /app
      command: npm run dev
      ports:
        - "5555:5555"
      volumes:
        - "./segmentation_microservice/:/app"

networks: 
  default: 
    external: 
      name: external-network